/** WMO weather interpretation codes → short Hebrew label + icon slug. */
export const WEATHER_CODES: Record<number, { he: string; icon: string }> = {
  0: { he: 'בהיר', icon: 'sun' },
  1: { he: 'בהיר בעיקר', icon: 'cloud-sun' },
  2: { he: 'מעונן חלקית', icon: 'cloud-sun' },
  3: { he: 'מעונן', icon: 'cloud' },
  45: { he: 'ערפל', icon: 'fog' },
  48: { he: 'ערפל', icon: 'fog' },
  51: { he: 'טפטוף קל', icon: 'rain' },
  53: { he: 'טפטוף', icon: 'rain' },
  55: { he: 'טפטוף חזק', icon: 'rain' },
  61: { he: 'גשם קל', icon: 'rain' },
  63: { he: 'גשם', icon: 'rain' },
  65: { he: 'גשם חזק', icon: 'rain' },
  66: { he: 'גשם מעורב קרח', icon: 'rain' },
  67: { he: 'גשם מעורב קרח', icon: 'rain' },
  71: { he: 'שלג קל', icon: 'snow' },
  73: { he: 'שלג', icon: 'snow' },
  75: { he: 'שלג כבד', icon: 'snow' },
  77: { he: 'גרגירי שלג', icon: 'snow' },
  80: { he: 'ממטרים', icon: 'rain' },
  81: { he: 'ממטרים', icon: 'rain' },
  82: { he: 'ממטרים עזים', icon: 'storm' },
  85: { he: 'ממטרי שלג', icon: 'snow' },
  86: { he: 'ממטרי שלג', icon: 'snow' },
  95: { he: 'סופת רעמים', icon: 'storm' },
  96: { he: 'סופת רעמים וברד', icon: 'storm' },
  99: { he: 'סופת רעמים וברד', icon: 'storm' },
};
