/** WMO weather interpretation codes → short Hebrew label + emoji. */
export const WEATHER_CODES: Record<number, { he: string; emoji: string }> = {
  0: { he: 'בהיר', emoji: '☀️' },
  1: { he: 'בהיר בעיקר', emoji: '🌤️' },
  2: { he: 'מעונן חלקית', emoji: '⛅' },
  3: { he: 'מעונן', emoji: '☁️' },
  45: { he: 'ערפל', emoji: '🌫️' },
  48: { he: 'ערפל', emoji: '🌫️' },
  51: { he: 'טפטוף קל', emoji: '🌦️' },
  53: { he: 'טפטוף', emoji: '🌦️' },
  55: { he: 'טפטוף חזק', emoji: '🌧️' },
  61: { he: 'גשם קל', emoji: '🌦️' },
  63: { he: 'גשם', emoji: '🌧️' },
  65: { he: 'גשם חזק', emoji: '🌧️' },
  66: { he: 'גשם מעורב קרח', emoji: '🌧️' },
  67: { he: 'גשם מעורב קרח', emoji: '🌧️' },
  71: { he: 'שלג קל', emoji: '🌨️' },
  73: { he: 'שלג', emoji: '🌨️' },
  75: { he: 'שלג כבד', emoji: '❄️' },
  77: { he: 'גרגירי שלג', emoji: '🌨️' },
  80: { he: 'ממטרים', emoji: '🌦️' },
  81: { he: 'ממטרים', emoji: '🌧️' },
  82: { he: 'ממטרים עזים', emoji: '⛈️' },
  85: { he: 'ממטרי שלג', emoji: '🌨️' },
  86: { he: 'ממטרי שלג', emoji: '❄️' },
  95: { he: 'סופת רעמים', emoji: '⛈️' },
  96: { he: 'סופת רעמים וברד', emoji: '⛈️' },
  99: { he: 'סופת רעמים וברד', emoji: '⛈️' },
};
